# Generated by Django 2.1.5 on 2019-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('vec', 'Vehicles'), ('prop', 'properties'), ('Mobile Phones & Accessories', 'Mobile'), ('Electronics & Home Appliances', 'Electronics'), ('Home & Garden', 'Home'), ('fasion & beauty', 'fashion'), ('pets', 'pets'), ('Kids&Babies', 'Kids'), ('sporting Goods &Bikes', 'sporting'), ('Hobbies Music Art &Books', 'Hobbies'), ('jobs', 'Jobs'), ('Business&Industrial', 'Business'), ('services', 'services')], max_length=120)),
                ('image', models.ImageField(null=True, upload_to='project_static/Advertise/img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
