# Generated by Django 2.1.5 on 2019-06-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20190622_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
