# Generated by Django 2.1.5 on 2019-06-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_advertise_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='user',
            new_name='publisher',
        ),
    ]
