# Generated by Django 2.1.5 on 2019-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0008_auto_20190624_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='category',
            field=models.CharField(choices=[('Vehicles', 'Vehicles'), ('Properties', 'Properties'), ('MobilePhones&Accessories', 'MobilePhones&Accessories'), ('Electronics&HomeAppliances', 'Electronics&HomeAppliances'), ('Home&Garden', 'Home&Garden'), ('Fashion', 'Fashion'), ('pets', 'Pets'), ('Kids&Babies', 'Kids&Babies'), ('SportingGoods&Bikes', 'SportingGoods&Bikes'), ('Hobbies,Music', 'Hobbies,Music'), ('jobs', 'Jobs'), ('Business&Industrial', 'Business&Industrial'), ('services', 'Services')], max_length=120),
        ),
    ]
