# Generated by Django 2.1.5 on 2019-06-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'contact us'},
        ),
    ]
